### Follow tag
POST http://localhost:8000/api/v1/follow_tag/3
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50IjoxLCJpZF9yb2xlIjoxLCJhY2NvdW50X25hbWUiOiJhZG1pbiIsInN0YXR1cyI6MCwiaWF0IjoxNjMwNzI0MjA1LCJleHAiOjE2MzA3Mjc4MDV9.jhYPQzcNO1L2FJJ-elPBW1K8o6EBT_gaLJupX0WClaQ


### unfollow tag
DELETE http://localhost:8000/api/v1/follow_tag/5
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50IjoxLCJpZF9yb2xlIjoxLCJhY2NvdW50X25hbWUiOiJhZG1pbiIsInN0YXR1cyI6MCwiaWF0IjoxNjMwNjgyNTI3LCJleHAiOjE2MzA2ODYxMjd9.sb0eDkAs9PPtVFDsjnYFHHE0rbj_Xq5aGjF9wLmm0q0



### unfollow all tag
DELETE http://localhost:8000/api/v1/follow_tag/
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50Ijo4LCJpZF9yb2xlIjoyLCJhY2NvdW50X25hbWUiOiJhYmNkIiwic3RhdHVzIjoyLCJpYXQiOjE2MzEwMDI5NDIsImV4cCI6MTYzMTAwNjU0Mn0.t7wNs48SWF_FthSujR5MDun3KZZC8k-NKq-zCe9fvWQ
