### Get a post by id
GET http://localhost:8000/api/v1/post/6
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50Ijo5LCJpZF9yb2xlIjozLCJhY2NvdW50X25hbWUiOiJodXkiLCJzdGF0dXMiOjAsImlhdCI6MTYzMDk4NTg2NSwiZXhwIjoxNjMwOTg5NDY1fQ.3rQMXJs3hzq4phl2-uPVpKIQpJYP6znJqwpip8SnA7U


### Post
POST http://localhost:8000/api/v1/post
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50IjoxLCJpZF9yb2xlIjoxLCJhY2NvdW50X25hbWUiOiJhZG1pbiIsInN0YXR1cyI6MCwiaWF0IjoxNjMwNDc4NTY3LCJleHAiOjE2MzA0ODIxNjd9.-9PbTPAKBFFI4UNkMG54tY86M-A0WeVvM7kLOX3ZPgY
Content-Type: application/json

{
    "title": "My title test post_tag",
    "content": "Ahihi vsđs",
    "tags": [
        1,2
    ]
}

### Cập nhật bài viết
PUT http://localhost:8000/api/v1/post/4
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50IjoxLCJpZF9yb2xlIjoxLCJhY2NvdW50X25hbWUiOiJhZG1pbiIsInN0YXR1cyI6MCwiaWF0IjoxNjMwNTczNjA5LCJleHAiOjE2MzA1NzcyMDl9.M1GsTRx_gWnVXtOFWGlcVs7aUCPJY_moZR_iUC7GNFM
Content-Type: application/json

{
    "title": "1234231",
    "content": "Ahihi nap, odsokvldsv  vsđs",
    "tags": [
        3,5
    ]
}


### Thay đổi status của bài viết
PUT http://localhost:8000/api/v1/post/3/status/1
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50IjoxLCJpZF9yb2xlIjoxLCJhY2NvdW50X25hbWUiOiJhZG1pbiIsInN0YXR1cyI6MCwiaWF0IjoxNjMwNDc4NTY3LCJleHAiOjE2MzA0ODIxNjd9.-9PbTPAKBFFI4UNkMG54tY86M-A0WeVvM7kLOX3ZPgY


### Thay đổi access của bài viế
PUT http://localhost:8000/api/v1/post/3/access/1
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50IjoxLCJpZF9yb2xlIjoxLCJhY2NvdW50X25hbWUiOiJhZG1pbiIsInN0YXR1cyI6MCwiaWF0IjoxNjMwNTEzNjQ0LCJleHAiOjE2MzA1MTcyNDR9.xBHx69NSBtcRPCPq2I24LQawt5wEHJpr2aasmGwObZU


### Xóa bài viết
DELETE http://localhost:8000/api/v1/post/6
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50Ijo4LCJpZF9yb2xlIjoyLCJhY2NvdW50X25hbWUiOiJhYmNkIiwic3RhdHVzIjoyLCJpYXQiOjE2MzA0ODczMjAsImV4cCI6MTYzMDQ5MDkyMH0.uJQ6LlbZ845g0UH1m_dYpyOBQjx6BU0ZPM8fqp0emeg


### Lấy danh sách bài viết mới nhất theo trang
GET http://localhost:8000/api/v1/post/newest?page=1

### Lấy danh sách bài viết bookmark theo trang
GET http://localhost:8000/api/v1/post/bookmark?page=1
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50Ijo2MCwiaWRfcm9sZSI6MSwiYWNjb3VudF9uYW1lIjoidmluaGl0IiwiaWF0IjoxNjQ0NDc3NjU2LCJleHAiOjE2NDY1NTEyNTZ9.kv3VB1JQnQmucFwAqa9R-w7ePJ4O9pUsGCNkmzUbVdA


### Lấy danh sách bài viết từ tài khoản và tag follow theo trang
GET http://localhost:8000/api/v1/post/following/1
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50Ijo4LCJpZF9yb2xlIjoyLCJhY2NvdW50X25hbWUiOiJhYmNkIiwic3RhdHVzIjoyLCJpYXQiOjE2MzA3Nzc5MTQsImV4cCI6MTYzMDc4MTUxNH0.gvH9aCoQ85MGDKwr6LMMe_Smkre-oWFhmlwY_hCm0eo


### Lấy danh sách bài viết NHÁP
GET http://localhost:8000/api/v1/post/drafts?page=1
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50Ijo2MCwiaWRfcm9sZSI6MSwiYWNjb3VudF9uYW1lIjoidmluaGl0IiwiaWF0IjoxNjQ0MjQyODc4LCJleHAiOjE2NDYzMTY0Nzh9.kV30ABaK52hIpMiA4L9NnMvDpZypNXnYcFCfLOflgT0

### Lấy danh sách bài viết PUBLIC
GET http://localhost:8000/api/v1/post/public?page=1
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50Ijo2MCwiaWRfcm9sZSI6MSwiYWNjb3VudF9uYW1lIjoidmluaGl0IiwiaWF0IjoxNjQ0MjQyODc4LCJleHAiOjE2NDYzMTY0Nzh9.kV30ABaK52hIpMiA4L9NnMvDpZypNXnYcFCfLOflgT0


### Lấy danh sách bài viết UNLISTED: Chỉ có link mới xem
GET http://localhost:8000/api/v1/post/unlisted?page=1
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50Ijo2MCwiaWRfcm9sZSI6MSwiYWNjb3VudF9uYW1lIjoidmluaGl0IiwiaWF0IjoxNjQ0MjQyODc4LCJleHAiOjE2NDYzMTY0Nzh9.kV30ABaK52hIpMiA4L9NnMvDpZypNXnYcFCfLOflgT0

### Lấy danh sách UP vote của bài viết
GET http://localhost:8000/api/v1/post/2/voteup


### Lấy danh sách DOWN vote của bài viết
GET http://localhost:8000/api/v1/post/1/votedown

### Lấy ĐIỂM vote của bài viết
GET http://localhost:8000/api/v1/post/1/vote

### Lấy danh sách bài viết theo status
GET http://localhost:8000/api/v1/post/status/1/1
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50IjoxLCJpZF9yb2xlIjoxLCJhY2NvdW50X25hbWUiOiJhZG1pbiIsInN0YXR1cyI6MCwiaWF0IjoxNjMxMDY4MTg0LCJleHAiOjE2MzEwNzE3ODR9.Vilkub32A9iXoiRH5YNt1JNTCXzqBTy2FaKlt4Y1Rls

### Lấy danh sách các bài viết mà bản thân đang follow
GET http://localhost:8000/api/v1/post/following?page=1
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50Ijo2MCwiaWRfcm9sZSI6MSwiYWNjb3VudF9uYW1lIjoidmluaGl0IiwiaWF0IjoxNjQxNDgwOTQ2LCJleHAiOjE2NDM1NTQ1NDZ9.zl7WzWBIycxgA_wrEbtto3oInLv-FrcHXSTxVybgsf0

###
GET http://localhost:8000/api/v1/post/trending?page=1
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50Ijo2MCwiaWRfcm9sZSI6MSwiYWNjb3VudF9uYW1lIjoidmluaGl0IiwiaWF0IjoxNjQxNDgwOTQ2LCJleHAiOjE2NDM1NTQ1NDZ9.zl7WzWBIycxgA_wrEbtto3oInLv-FrcHXSTxVybgsf0

### 
GET http://localhost:8000/api/v1/post/browse?page=1
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50Ijo2MCwiaWRfcm9sZSI6MSwiYWNjb3VudF9uYW1lIjoidmluaGl0IiwiaWF0IjoxNjQ0MjQyODc4LCJleHAiOjE2NDYzMTY0Nzh9.kV30ABaK52hIpMiA4L9NnMvDpZypNXnYcFCfLOflgT0

### 
GET http://localhost:8000/api/v2/post/spam?page=1
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50Ijo2MCwiaWRfcm9sZSI6MSwiYWNjb3VudF9uYW1lIjoidmluaGl0IiwiaWF0IjoxNjQ0MjQyODc4LCJleHAiOjE2NDYzMTY0Nzh9.kV30ABaK52hIpMiA4L9NnMvDpZypNXnYcFCfLOflgT0

### Search
GET http://localhost:8000/api/v1/post/search?k=vinh&page=2
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50Ijo2MCwiaWRfcm9sZSI6MSwiYWNjb3VudF9uYW1lIjoidmluaGl0IiwiaWF0IjoxNjQ0MjQyODc4LCJleHAiOjE2NDYzMTY0Nzh9.kV30ABaK52hIpMiA4L9NnMvDpZypNXnYcFCfLOflgT0
